### ISSUE TITLE
Incorrect version resolution for some tools (e.g. octopus.dotnet.cli)

### ISSUE THREAD

**Issue by augustoproiete** [rychlym/dotnet-tools-outdated#2]
Hey @rychlym, I'm using the latest version of `dotnet-tools-outdated` as of this writing (v0.4.1) and for some tools it's suggesting updating the tool to an incorrect version (not the latest).

For example, I have [`octopus.dotnet.cli`](https://www.nuget.org/packages/Octopus.DotNet.Cli) version `7.4.2` installed as a global tool. The latest version right now is `7.4.4`.

Running `dotnet tools-outdated` suggests a new version available `2018.4.0-enh-workersinclien13` (which existed one day, but have been unlisted).

![image](https://user-images.githubusercontent.com/177608/100040580-f072a680-2ddd-11eb-8752-37d23a466ce6.png)

### Repro steps:

```
dotnet tool install octopus.dotnet.cli --version 7.4.2 -g
dotnet tool install dotnet-tools-outdated --version 0.4.1 -g
dotnet tools-outdated
```

**Comment by rychlym** [comment]
Hi @augustoproiete  
Thanks for reporting the issue
The dotnet-tools outdated simply takes the latest item from the result following nuget api call,
https://api.nuget.org/v3-flatcontainer/Octopus.DotNet.Cli/index.json

To solve this bug:
I will try to find nuget api call to get whether the version is unlisted, at this moment, I would appreciate any advice, which nuget api to call for this purpose.

.

**Comment by rychlym** [comment]
Hi,
I have found a little different solution based on [this](https://github.com/vscode-contrib/vscode-versionlens/issues/108) - using a different api call.
https://api-v2v3search-0.nuget.org/autocomplete?id={packageid}&prerelease={trueorfalseval}

So hopefully it is fixed, I have just released the new version. (0.5.0)
I should note, that with this fix is also coming one breaking change - not taking the pre-release versions by default too.
Because I think, it would be better to be more conservative by default. (If you would like check the pre-release versions, please add the -pre or --prerelease parameter to the command line).

**Comment by augustoproiete** [comment]
@rychlym Thanks a lot! Appreciate the quick fix and release!
